name: mapesa
description: "Track MPESA transactions"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cron: ^0.6.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  provider: ^6.0.5
  telephony: ^0.2.0
  shared_preferences: ^2.0.16

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env
