name: mapesa
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_sms_inbox: ^1.0.2
  fluttertoast: ^8.1.2
  permission_handler: ^11.1.0
  provider: ^6.0.5
  telephony: ^0.2.0
  shared_preferences: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
