name: widgetbook_workspace

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    widgetbook_annotation: ^3.2.0
    widgetbook: ^3.9.0
    mapesa:
        path: ../

dev_dependencies:
    build_runner:
    widgetbook_generator: ^3.9.0

flutter:
    uses-material-design: true
