name: Flutter CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.3

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test --no-pub --reporter github --coverage  

      - name: Build APK
        run: flutter build apk --release 